[package]
name = "bonk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
caveman = { path = "../libcaveman" }
clap = { version = "4.3.21", features = [ "derive" ] }
hex = "0.4.3"
protobuf = "3.2.0"
serde = { version = "1.0.183", features = [ "derive" ] }
serde_json = "1.0.105"
sha2 = "0.10.7"
zstd = "0.12.4"
